name: 'Normalize data in MongoDB'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  MONGODB_URL: ${{ secrets.MONGODB_URL }}

jobs:
  normalize-mongodb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: 'Create env file'
        run: |
          touch .env.development
          echo MONGODB_URL=${{ secrets.MONGODB_URL }} >> .env.development
          cat .env.development

      - name: Run normalize
        run: pnpm run mongodb:normalize
